---
- name: Rollback Apache Web Server
  hosts: web_servers
  become: yes
  
  tasks:
    - name: Revert to Previous Apache Version
      yum:
        name: "httpd-2.4.56"
        state: present

    - name: Restart Apache Service
      service:
        name: httpd
        state: restarted

    - name: Log Rollback Action
      lineinfile:
        path: ../logs/rollback.log
        line: "Rollback performed on {{ ansible_date_time.date }} due to deployment failure"
        create: yes
